let cezalar = [
    { "isim": "Нарушение правил светофора (1)", "para": 500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 1 },
    { "isim": "Превышение лимита скорости на 5+ (1)", "para": 500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 1 },
    { "isim": "Превышение лимита скорости на 10+", "para": 1000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Превышение лимита скорости на 20+", "para": 1500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Превышение лимита скорости на 30+", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Движение нелегального автомобиля по дороге (4)", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 4 },
    { "isim": "Управление транспортным средством без лицензии (10)", "para": 3000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 10 },
    { "isim": "Незаконная парковка (1)", "para": 500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 1 },
    { "isim": "Съезд с места происшествия (4)", "para": 5000, "hapis": 0, "kamu": 10, "illegal": false, "active": false, "tceza": 4 },
    { "isim": "Незаконная модификация автомобиля (4)", "para": 1500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 4 },
    { "isim": "Безрассудное вождение (1)", "para": 5000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 1 },
    { "isim": "Незаконные уличные гонки", "para": 2500, "hapis": 0, "kamu": 30, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Взяточничество государственного служащего", "para": 1500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Оскорбление государственного служащего", "para": 500, "hapis": 0, "kamu": 20, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Угроза сотруднику правоохранительных органов", "para": 2500, "hapis": 0, "kamu": 20, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Мошенничество", "para": 2500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Проституция", "para": 5000, "hapis": 0, "kamu": 30, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Киберпреступность", "para": 3000, "hapis": 0, "kamu": 20, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Кража государственного транспортного средства (5)", "para": 7500, "hapis": 50, "kamu": 0, "illegal": false, "active": false, "tceza": 5 },
    { "isim": "Грабеж (3)", "para": 7000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 3 },
    { "isim": "Беспорядочное поведение", "para": 3500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Нападение", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Нападение на государственного служащего", "para": 8000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Сопротивление аресту", "para": 5000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Мошенническая деятельность", "para": 4500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Неисполнение предупреждения остановки (4)", "para": 3000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 4 },
    { "isim": "Лжесвидетельство", "para": 7500, "hapis": 0, "kamu": 30, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Связан с незаконной организацией (10)", "para": 10000, "hapis": 500, "kamu": 0, "illegal": false, "active": false, "tceza": 10 },
    { "isim": "Умышленное убийство по неосторожности", "para": 15000, "hapis": 0, "kamu": 10, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Похищение", "para": 10000, "hapis": 10, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Похищение государственного служащего", "para": 15000, "hapis": 30, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Незаконные ставки", "para": 3000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Акт терроризма (10)", "para": 100000, "hapis": 1000, "kamu": 0, "illegal": false, "active": false, "tceza": 10 },
    { "isim": "Подстрекательство или помощь в совершении преступления", "para": 3000, "hapis": 60, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Поднятие оружия", "para": 3500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Получение коктейля Молотова", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Фальшивый номер (2)", "para": 2500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Стрельба, связанная с бандой", "para": 5000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Взятие заложника", "para": 10000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Покушение на убийство", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Убийство второй степени", "para": 10000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Убийство первой степени", "para": 15000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Покушение на убийство государственного служащего", "para": 10000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Убийство второй степени государственного служащего", "para": 12500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Убийство первой степени государственного служащего", "para": 17500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Покушение на вооруженное ограбление", "para": 15000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Вооруженное ограбление", "para": 20000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Причастность к вооруженному ограблению", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Покушение на ограбление", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Ограбление", "para": 12500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Причастность к ограблению", "para": 5000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Поддельное представление государственного служащего", "para": 3500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Причастность к побегу из тюрьмы", "para": 5500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Попытка побега из тюрьмы", "para": 6000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Побег из тюрьмы", "para": 10000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Вандализм", "para": 4500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Вандализм государственной собственности", "para": 6000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Незаконное проникновение", "para": 6500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Тяжкое незаконное проникновение", "para": 9000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Поджог", "para": 12500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Харассмент (домогательство)", "para": 2500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Ложные отчеты", "para": 2750, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Владение украденной идентификацией", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Преследование", "para": 1500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Уклонение", "para": 7000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Безрассудное уклонение", "para": 7500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Вождение в состоянии опьянения", "para": 8000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Вождение без фар и сигналов", "para": 1750, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Незаконный разворот", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Незаконное обгон", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Неостановка", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Неуступка места экстренному транспорту", "para": 4000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Отсутствие правил движения (4)", "para": 1500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 4 },
    { "isim": "Управление транспортным средством с нарушением личных правил (2)", "para": 5000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Незаконная парковка государственного транспорта (1)", "para": 500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 1 },
    { "isim": "Бродячие животные", "para": 750, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 0 },
    { "isim": "Запрещено въезжать (2)", "para": 1000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Отсутствие документов (2)", "para": 3000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Потеря удостоверения личности (2)", "para": 1000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Вождение без удостоверения (2)", "para": 2500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Вождение без регистрации транспорта (2)", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Вождение без страховки (2)", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Вождение государственного транспорта без разрешения (2)", "para": 2000, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 },
    { "isim": "Вождение государственного транспорта с нарушением правил (2)", "para": 2500, "hapis": 0, "kamu": 0, "illegal": false, "active": false, "tceza": 2 }
];
